function IntroductioToVariables(){
    var car="toyota"
    var y=20              
    console.log(car)   
    console.log(y)
}
IntroductioToVariables()


function addition(){
    // addition
var z=40
var x=30
var sum=z+x
console.log(sum)
}
addition()


function division (){
    // division
var div1 =144
var div2 =12
var divisionAns = div1 / div2
console.log(divisionAns)
}
division()


function multilication(){
   // multilication
var mul1 =26
var mul2 =26
var multilicationAns = mul1 * mul2
console.log(multilicationAns) 
}
multilication()


function subtruction(){
// subtruction
var sub1 =80
var sub2 =40
var subtructionAns = sub1-sub2
console.log(subtructionAns)
}
subtruction()


function CheckName(){
 // conditions
var age= 12

if(age >= 12){

    //do something
    console.log("is above 12")
}

else{
    //do sommething else
    console.log("is not above 12")
}
}
CheckName()


function CheckColor(){
    var favorite_color ="Blue"

if(favorite_color == "Blue"){
    console.log("correct")
}

else{
    console.log("incorrect")
}
}
CheckColor()

