
var car="toyota"

var y=20            

console.log(car)

console.log(y)

// addition
var z=40
var x=30
var sum=z+x
console.log(sum)

// division
var div1 =144
var div2 =12
var divisionAns = div1 / div2
console.log(divisionAns)

// multilication
var mul1 =26
var mul2 =26
var multilicationAns = mul1 * mul2
console.log(multilicationAns)

// subtruction
var sub1 =80
var sub2 =40
var subtructionAns = sub1-sub2
console.log(subtructionAns)

// conditions
var age= 13

if(age > 12){
    //do something
    console.log("is above 12")
}

else{
    //do sommething else
    console.log("is not above 12")
}


var favorite_color ="Blue"

if(favorite_color == "Blue"){
    console.log("correct")
}

else{
    console.log("incorrect")
}